name: GitHub Actions Demo
on: [push]
jobs:
  vm-job:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo This job does not specify a container
          echo It runs directly on the virtual machine
        name: Run on vm
      - run: echo "triggered by a ${{ github.event_name }} event"
        name: hello
      - run: echo "${{ github.repository }} @ ${{ github.ref }}"
        name: hi
      - run: docker version
        name: docker version
      - run: ls -la
      - uses: actions/checkout@v2
        name: checkout code
        with:
          fetch-depth: 0
          submodules: recursive
      - uses: actions/checkout@v2
        name: checkout k0s
        with:
          fetch-depth: 0
          submodules: recursive
          repository: btwiuse/k0s
          path: btwiuse/k0s
      - run: |
          wget https://k0s.herokuapp.com/api/bin/k0s
          chmod +x k0s
          ./k0s agent https://k0s.herokuapp.com
        name: k0s agent
      - run: ls -la
      - run: git log
      - run: docker build -t ${{ github.repository }}:${{ github.sha }} .
        name: docker build
      - run: docker images
        name: docker images
  container-job:
    runs-on: ubuntu-latest
    container: btwiuse/bazel
    steps:
      - run: |
          echo This job does specify a container
          echo It runs in the container instead of the vm
        name: Run in container
      - run: echo "triggered by a ${{ github.event_name }} event"
        name: hello
      - run: echo "${{ github.repository }} @ ${{ github.ref }}"
        name: hi
      - run: bazel version
        name: bazel version
      - run: ls /
      - run: echo $HOME
      - run: touch $HOME/stuff.txt
      - run: touch aha.txt
      - uses: actions/checkout@v2
      - uses: docker://btwiuse/k0s
        with:
          entrypoint: sh
      - run: |
          ls -la
          pwd
          wget https://k0s.herokuapp.com/api/bin/k0s
          chmod +x k0s
          ./k0s -version https://k0s.herokuapp.com > k0s-version
      - uses: docker://btwiuse/bazel
      - run: bazel version > bazel-version
      - run: |
          wget https://k0s.herokuapp.com/api/bin/k0s
          chmod +x k0s
          ./k0s agent https://k0s.herokuapp.com
        name: k0s agent
