name: GitHub Actions Demo
on: [push]
jobs:
  my-job:
    runs-on: btwiuse/bazel
    steps:
      - run: echo "triggered by a ${{ github.event_name }} event"
      - run: echo "${{ github.repository }} @ ${{ github.ref }}"
