name: GitHub Actions Demo
on: [push]
jobs:
  vm-job:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo This job does not specify a container
          echo It runs directly on the virtual machine
        name: Run on vm
      - run: echo "triggered by a ${{ github.event_name }} event"
        name: hello
      - run: echo "${{ github.repository }} @ ${{ github.ref }}"
        name: hi
      - run: docker version
        name: docker version
      - run: ls -la
      - run: docker build .
        name: docker build
      - uses: actions/checkout@v2
      - run: ls -la
      - run: docker build .
        name: docker build
  container-job:
    runs-on: ubuntu-latest
    container: btwiuse/bazel
    steps:
      - run: |
          echo This job does specify a container
          echo It runs in the container instead of the vm
        name: Run in container
      - run: echo "triggered by a ${{ github.event_name }} event"
        name: hello
      - run: echo "${{ github.repository }} @ ${{ github.ref }}"
        name: hi
      - run: bazel version
        name: bazel version
