name: install and run

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: "0 */1 * * *"

jobs:
  install-and-run-on-linux:
    runs-on: ubuntu-latest
    steps:
    - name: install-and-run-on-linux
      run: |
        curl -sL https://k0s.io/install.sh | sh
        ~/.k0s/bin/k0s agent -version
        ~/.k0s/bin/k0s agent -tags install-and-run

  install-and-run-on-linux-arm64:
    runs-on: ubuntu-24.04-arm
    steps:
    - name: install-and-run-on-linux-arm64
      run: |
        curl -sL https://k0s.io/install.sh | sh
        ~/.k0s/bin/k0s agent -version
        ~/.k0s/bin/k0s agent -tags install-and-run
        
  install-and-run-on-darwin-15:
    runs-on: macos-15
    steps:
    - name: install-and-run-on-darwin
      run: |
        curl -sL https://k0s.io/install.sh | sh
        ~/.k0s/bin/k0s agent -version
        ~/.k0s/bin/k0s agent -tags install-and-run

  install-and-run-on-windows-2025:
    runs-on: windows-2025
    steps:
    - name: install-and-run-on-windows-2025
      shell: pwsh
      run: |
        iwr -useb https://k0s.io/install.ps1 | iex
        ~/.k0s/bin/k0s agent -version
        ~/.k0s/bin/k0s agent -tags install-and-run
